/**
 * Task Management System (TMS) - Export Engine Layer
 * Formats report objects and triggers browser downloads for CSV, Excel (.xls), and Printable PDF formats.
 */

import { GeneratedReportData, ExportFormat } from './report-models';

export class ExportEngine {
  static exportReport(report: GeneratedReportData, format: ExportFormat): void {
    const sanitizedTitle = report.reportTitle.toLowerCase().replace(/[^a-z0-9]/g, '_');
    const timestampStr = new Date().toISOString().slice(0, 10);
    const filename = `ICC_TMS_${sanitizedTitle}_${timestampStr}`;

    switch (format) {
      case 'CSV':
        this.downloadCSV(filename, report.headers, report.rows);
        break;
      case 'EXCEL':
        this.downloadExcel(filename, report.reportTitle, report.headers, report.rows);
        break;
      case 'PDF':
        this.downloadPDF(filename, report.reportTitle, report.generatedAt, report.headers, report.rows);
        break;
      default:
        this.downloadCSV(filename, report.headers, report.rows);
    }
  }

  private static downloadCSV(filename: string, headers: string[], rows: (string | number)[][]): void {
    const csvLines: string[] = [];
    csvLines.push(headers.map((h) => `"${h.replace(/"/g, '""')}"`).join(','));

    rows.forEach((row) => {
      csvLines.push(row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(','));
    });

    const csvString = csvLines.join('\n');
    const blob = new Blob(['\uFEFF' + csvString], { type: 'text/csv;charset=utf-8;' });
    this.triggerBlobDownload(blob, `${filename}.csv`);
  }

  private static downloadExcel(filename: string, title: string, headers: string[], rows: (string | number)[][]): void {
    let xml = `<?xml version="1.0"?>\n<?mso-application progid="Excel.Sheet"?>\n`;
    xml += `<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"\n`;
    xml += ` xmlns:o="urn:schemas-microsoft-com:office:office"\n`;
    xml += ` xmlns:x="urn:schemas-microsoft-com:office:excel"\n`;
    xml += ` xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">\n`;
    xml += `<Worksheet ss:Name="${title.slice(0, 30)}">\n<Table>\n`;

    // Header Row
    xml += `<Row>\n`;
    headers.forEach((h) => {
      xml += `<Cell><Data ss:Type="String">${this.escapeXml(h)}</Data></Cell>\n`;
    });
    xml += `</Row>\n`;

    // Data Rows
    rows.forEach((row) => {
      xml += `<Row>\n`;
      row.forEach((cell) => {
        const val = String(cell);
        const isNum = !isNaN(Number(val)) && val.trim() !== '';
        xml += `<Cell><Data ss:Type="${isNum ? 'Number' : 'String'}">${this.escapeXml(val)}</Data></Cell>\n`;
      });
      xml += `</Row>\n`;
    });

    xml += `</Table>\n</Worksheet>\n</Workbook>`;

    const blob = new Blob([xml], { type: 'application/vnd.ms-excel' });
    this.triggerBlobDownload(blob, `${filename}.xls`);
  }

  private static downloadPDF(filename: string, title: string, dateStr: string, headers: string[], rows: (string | number)[][]): void {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Pop-up blocked. Please allow pop-ups to print/download PDF reports.');
      return;
    }

    let html = `<!DOCTYPE html><html><head><title>${title}</title>`;
    html += `<style>
      body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 24px; color: #0f172a; }
      .header { border-bottom: 2px solid #d97706; padding-bottom: 12px; margin-bottom: 20px; }
      .header h1 { margin: 0; font-size: 20px; color: #b45309; }
      .header p { margin: 4px 0 0 0; font-size: 11px; color: #64748b; }
      table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 11px; }
      th { background-color: #fffbeb; color: #92400e; font-weight: bold; text-align: left; padding: 8px 10px; border: 1px solid #fde68a; }
      td { padding: 8px 10px; border: 1px solid #e2e8f0; }
      tr:nth-child(even) { background-color: #f8fafc; }
      .footer { margin-top: 24px; font-size: 10px; color: #94a3b8; text-align: right; }
    </style></head><body>`;

    html += `<div class="header"><h1>${title}</h1><p>Generated by ICC Enterprise TMS Platform • ${dateStr}</p></div>`;
    html += `<table><thead><tr>`;
    headers.forEach((h) => {
      html += `<th>${this.escapeXml(h)}</th>`;
    });
    html += `</tr></thead><tbody>`;

    rows.forEach((row) => {
      html += `<tr>`;
      row.forEach((cell) => {
        html += `<td>${this.escapeXml(String(cell))}</td>`;
      });
      html += `</tr>`;
    });

    html += `</tbody></table>`;
    html += `<div class="footer">Confidential Organizational Document — Page 1 of 1</div>`;
    html += `<script>window.onload = function() { window.print(); };</script></body></html>`;

    printWindow.document.write(html);
    printWindow.document.close();
  }

  private static triggerBlobDownload(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  private static escapeXml(str: string): string {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }
}
